FROM openjdk:17

ENV APP_NAME=users-0.0.1-SNAPSHOT
ENV APP_WORKDIR=app
ENV DB_OPTS="-DDATABASE_HOST=users-db:5432 -DDATABASE_NAME=users -DDATABASE_USERNAME=postgres -DDATABASE_PASSWORD=postgresPassword"

RUN mkdir /$APP_WORKDIR
COPY build/libs/$APP_NAME.jar /$APP_WORKDIR
WORKDIR /$APP_WORKDIR
CMD java -jar $DB_OPTS $APP_NAME.jar