version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresPassword
    ports:
      - "5432:5432"