version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresPassword
    ports:
      - 5432:5432