spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:14:////user_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true

logging:
  level:
    ru.social_network.users: DEBUG